sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
notifications:
  email:
    on_success: never

cache:
  directories:
    - node_modules

before_script:
  - npm prune
      
script:
  - npm run test-cov

after_script:
  # only upload the coverage.json file
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
